export const demoProjects = [
  {
    id: "project-late-moon",
    name: "迟来的月光",
    genre: "都市逆袭",
    episodeCount: 42,
    progress: 72,
    status: "生产中",
    outputs: 18,
    updatedAt: "刚刚",
    accent: "#ff6b4a",
  },
  {
    id: "project-medicine",
    name: "药香满园",
    genre: "古风种田",
    episodeCount: 36,
    progress: 46,
    status: "待审片",
    outputs: 8,
    updatedAt: "18 分钟前",
    accent: "#d3f16d",
  },
  {
    id: "project-heir",
    name: "继承者游戏",
    genre: "豪门悬疑",
    episodeCount: 28,
    progress: 100,
    status: "已完成",
    outputs: 32,
    updatedAt: "昨天",
    accent: "#8ca8ff",
  },
] as const;

export const demoJobs = [
  {
    id: "job-1",
    project: "迟来的月光",
    stage: "前贴生成",
    model: "Seedance 2.0",
    status: "running",
    progress: 68,
    time: "02:14",
  },
  {
    id: "job-2",
    project: "药香满园",
    stage: "高光智剪",
    model: "AI MediaKit",
    status: "review",
    progress: 100,
    time: "06:42",
  },
  {
    id: "job-3",
    project: "继承者游戏",
    stage: "合成导出",
    model: "AI MediaKit",
    status: "completed",
    progress: 100,
    time: "01:37",
  },
] as const;
